# Test OAuth client credentials
CLIENT_ID=unTESTsmTESTjkTESTDFY2ppWydKxXhQCBCgLfvE
CLIENT_SECRET=nXTESTNtTESTrKTESTRtnzZff6dHxEfij9rllHikcqv8gx0CMjMJfRBVuq6ZoWm8BoB92pMaHKc0Mz0sGdUuTJmuJmTCwSXwFDuOi5T2ja76jJdt6zSQuEMDpA7bbJem
